### PR TITLE
Update nametags to use RML from Alexa, added key hold for revive with…

### PR DESCRIPTION
**Pull request by dexslab**
… 5 second timer

### CODE REVIEW

**Comment by Stuyk** [comment]
I will look at this more in-depth when I can. It's a good PR just need time to dig into it more.

**Comment by DomePlaysHD** [comment]
I think it would be better if you have to press the key for revive for accessibility reasons. For some people, it's difficult to keep the button pressed.

**Comment by dexslab** [comment]
I could convert it to a setting instead where you can configure the time out 😃

**Comment by dexslab** [comment]
Issue i had was the keybinds only work for one thing we cannot reregister a keybind with Athena. Since this was a full Athena based solution i did not register via keydown or up events in alt:V

**Review by BigBoyLeft — APPROVED** [review]

**Pull request closed without merging**
